### ISSUE TITLE
hoobs 3.2 Issue

### ISSUE THREAD

**Issue by davidwhicker** [jonathandann/homebridge-yalealarmsystem#2]
Hello

Your plugin appears to break Hoobs Homebridge service from running on Hoobs latest update. I am unsure if this is a generic case to latest homebridge version or just latest hoobs version 3.2. 

I would be greatful if you can look into it as I use your plugin every day.

**Comment by davidwhicker** [comment]
02/05/2020, 08:05:12 [Burglar Alarm] Initializing YaleSyncAlarm platform...
02/05/2020, 08:05:12 Error: Cannot update reachability on non-bridged accessory!
    at Accessory._this.updateReachability (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:259:23)
    at Platform.updateReachability (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/platform.js:88:37)
    at YaleSyncPlatform.configurePanel (/home/hoobs/.hoobs/node_modules/homebridge-yalesyncalarm/dist/YaleSyncPlatform.js:382:23)
    at YaleSyncPlatform.configureAccessory (/home/hoobs/.hoobs/node_modules/homebridge-yalesyncalarm/dist/YaleSyncPlatform.js:235:22)
    at Server.configCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:332:26)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:95:14)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
